license, better source test, install/exit handling - added dbus-x11 to enable Ubuntu 19.04   like others

diff --git a/afterfailure b/afterfailure
--- a/afterfailure
+++ b/afterfailure
@@ -1,13 +1,35 @@
 #!/bin/bash
 
-if [[ "$BUILDTYPE" == "cmake-make" ]] || [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
+# gnucash-dev-docker: Docker containers for automated OS setup and dev/build environ for gnucash v3+ binaries and docs
+# Copyright (C) 2019 Dale Phurrough <dale@hidale.com>
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License along
+# with this program; if not, write to the Free Software Foundation, Inc.,
+# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+
+if [ "$BUILDTYPE" = "cmake-make" ] || [ "$BUILDTYPE" = "cmake-ninja" ]; then
     echo "########################"
     echo "##### LastTest.log #####"
     echo "########################"
     cat /build/Testing/Temporary/LastTest.log
 else
-    echo "Unknown BUILDTYPE: \"$BUILDTYPE\", cannot create failure information."
+    echo "Unknown BUILDTYPE: \"$BUILDTYPE\", cannot provide failure information"
 fi
 
-# This script should fail so that the entire script will fail.
-#exit 1
+if [ "$EXIT_AFTER_TEST" = "1" ]; then
+    exit 1
+fi
+
+# prevent container from immediately exiting
+#exec tail -f /dev/null
+exec bash
