appveyor commit hash of tags,head,sha

diff --git a/ci/appveyor.yml b/ci/appveyor.yml
--- a/ci/appveyor.yml
+++ b/ci/appveyor.yml
@@ -18,15 +18,36 @@ cache:
 install:
 - sh: |
     #!/bin/bash
+    # This script is only needed for when these CI files are in a separate repo than the core GnuCash repo
+    set -x
     set -e
     if [[ (-z "$GNC_GIT_CHECKOUT") || (-z "$APPVEYOR_BUILD_ID") ]]; then
       echo 'Error. GNC_GIT_CHECKOUT and APPVEYOR_BUILD_ID env variables are not defined' >&2
       exit 1
     fi
     if [[ ! -e gnucash.commithash.cached || -z "$(egrep "${APPVEYOR_BUILD_ID}$" gnucash.commithash.cached)" ]]; then
-      COMMITHASH="$(git ls-remote -h -t https://github.com/Gnucash/gnucash.git ${GNC_GIT_CHECKOUT} | cut -f 1)"
-      if [ -z "$COMMITHASH" ]; then
-        if curl --silent --fail --head --location --retry 2 --connect-timeout 5 --output /dev/null https://github.com/Gnucash/gnucash/commit/${GNC_GIT_CHECKOUT}; then
+      OBJECTHASH="$(git ls-remote -h -t https://github.com/Gnucash/gnucash.git ${GNC_GIT_CHECKOUT})"
+      if [ -n "$OBJECTHASH" ]; then
+        PATTERN='^([[:graph:]]+)[[:space:]]+refs/(heads|tags)'
+        if [[ "$OBJECTHASH" =~ $PATTERN ]]; then
+          if [[ "${BASH_REMATCH[2]}" == "heads" ]]; then
+            COMMITHASH="${BASH_REMATCH[1]}"
+          else
+            if curl --silent --fail --location --retry 3 --connect-timeout 5 --output tag.commithash.json https://api.github.com/repos/gnucash/gnucash/git/tags/${BASH_REMATCH[1]}; then
+              sudo apt-get --yes install jq
+              TMPHASH="$(< tag.commithash.json jq --raw-output --exit-status '.object.sha')"
+              if [ "$?" == "0" ]; then
+                COMMITHASH="$TMPHASH"
+              fi
+            fi
+          fi
+        fi
+        if [ -z "$COMMITHASH" ]; then
+          echo 'Error. GNC_GIT_CHECKOUT env variable returned unexpected ref from git repository' >&2
+          exit 1
+        fi
+      else
+        if curl --silent --fail --head --location --retry 3 --connect-timeout 5 --output /dev/null https://github.com/Gnucash/gnucash/commit/${GNC_GIT_CHECKOUT}; then
           COMMITHASH="${GNC_GIT_CHECKOUT}"
         else
           echo 'Error. GNC_GIT_CHECKOUT env variable is not a valid GnuCash git repo ref or commit hash' >&2
